### ISSUE TITLE
The engine plan file is not compatible with this version of TensorRT, expecting library version 5.1.5 got 5.1.6, please rebuild.

### ISSUE THREAD

**Issue by cvmk95** [smellslikeml/ActionAI#17]
`[TensorRT] ERROR: The engine plan file is not compatible with this version of TensorRT, expecting library version 5.1.5 got 5.1.6, please rebuild.
Traceback (most recent call last):
  File "experimental/teachable_machine.py", line 7, in <module>
    import poses
  File "/home/xxxx/ActionAI/experimental/poses.py", line 19, in <module>
    model_trt.load_state_dict(torch.load(OPTIMIZED_MODEL))
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 824, in load_state_dict
    load(self)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 819, in load
    state_dict, prefix, local_metadata, True, missing_keys, unexpected_keys, error_msgs)
  File "/usr/local/lib/python3.7/site-packages/torch2trt/torch2trt.py", line 309, in _load_from_state_dict
    self.context = self.engine.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'
`
how to suppose fix issue mentioned above? actually i tried to run on laptop which is installed tensorrt 5.1.5, or this cannot be run on device other than jetson nano?

**Comment by Stancoo** [comment]
same story. I'm just wondering what is 5.1.6  - there is nothing like that on nvidia tensorrt website
