### ISSUE TITLE
train_sequential.py is missing the PoseExtractor, or requires a different preprocess.py

### ISSUE THREAD

**Issue by KyleHarrison** [smellslikeml/ActionAI#28]
Hello,

Just wondering if I'm missing something or if _train_sequential.py_ is currently a template?  

`dataset = pd.read_csv('data/data.csv',  index_col=None)
` 
If _data.csv_ is generated by _preprocess.py_ it is a csv list of all image paths. Reshaping a _data.csv_ with:

`X_test = X_test.reshape(X_test.shape[0], pose_vec_dim, window)
`
How is it reshaped unless _data.csv_ is constructed in a different format like an image being transformed and its feature vector being recorded.

**Comment by gooohjy** [comment]
From my understanding, I believe that you're right. I managed to preprocess my images with [trt_pose](https://github.com/NVIDIA-AI-IOT/trt_pose) after modifying and merging codes from _transformer.py_ and _preprocess.py_. The output was a .csv file with 37 columns (36 x, 1 y variable). However, I was unable to run _train_sequential.py_ right away because of the `window` variable. 

I don't truly understand what the `window` variable is supposed to do. The default _train_sequential.py_ file has `window = 3` while the _train_legday.py_ example under _/examples/yogai_ has `window = 5`. Without adjusting the `window` variable, the following error pops up.

```
>>> X_test = X_test.reshape(X_test.shape[0], pose_vec_dim, window)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: cannot reshape array of size 124920 into shape (3470,36,3)
>>> X_train = X_train.reshape(X_train.shape[0], pose_vec_dim, window)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: cannot reshape array of size 499608 into shape (13878,36,3)
```
In the sample file _squats_deadlifts_stand5.csv_, there are 141 columns (140 x, 1 y variable). The model used in this example produces 28 points (unlike trt_pose above which produces 36 points) and I figured that the model must have no. of x variables = no. of points * window (140 = 28 * 5). Thus, when I adjusted to `window=1` in my file, I was able to train my model using _train_sequential.py_ (since 36 = 36 * 1 for my case). I was wondering what the `window` variable does and will there be any repercussions by adjusting my window variable to 1. Also, I would be glad to share my code that I used to preprocess my images if anyone needs them.

**Comment by gohjiayi** [comment]
Hi, just an update which may help you. In _iva.py_ there is a variable WRITE2CSV and from there, you can tweak the code to process training videos and save the data into csv file. From there, you can run _train_sequential.py_ and the model will be able to detect your custom actions.

**Comment by lweingart** [comment]
Hello @gohjiayi,

I'm coming today facing the same issue as you did at the time.
I would like to try and use train_sequential.py to train my own action recognition model, but as noticed a year ago, it is not exactly ready for the task as is.

It would seem that you managed to find a solution. Would you mind detailing it a bit more, to help me successfully prepare the dataset (or the csv file) and train the model ?

Thank you for your esteemed help
Cheers

**Comment by gohjiayi** [comment]
Sharing the codes I've used to generate the csv data on a Google Drive link [here](https://drive.google.com/file/d/1a-atdrizuk5x_0c_p1MSA_DhPTeFA7_h/view?usp=sharing). Note that I've used a 36 point pose estimation library instead so you might want to change to 28. It'll be fantastic if someone can use this to create a PR and document it down for future references. 😄

**Comment by aidynabirov** [comment]
Hello @gohjiayi,
Thanks a lot for your share! I tried to use it, but I have missing files, such as "trt_pose.coo, trt_pose.models, torch2trt". Can I ask, where did you get them?

**Comment by gohjiayi** [comment]
@aidynabirov You'll have to install the [trt_pose](https://github.com/NVIDIA-AI-IOT/trt_pose) dependency as indicated in the README. Not too sure what device you're working on but I've previously used a NVIDIA Jetson Nano.

**Comment by aidynabirov** [comment]
@gohjiayi, what was your torch version for installing trt_pose? I'm working on my laptop (GeForce GTX 1050). Thanks in advance!

**Comment by gohjiayi** [comment]
@aidynabirov I can't really recall given that it was quite some time back and I'm no longer using my Jetson Nano.. Apologies I can't advise you on this one!

**Comment by aidynabirov** [comment]
@gohjiayi, thanks a lot for your advice! I installed all dependencies, and at last, it asked me for "human_pose.json". I downloaded this JSON file from "https://github.com/NVIDIA-AI-IOT/trt_pose/blob/master/tasks/human_pose/human_pose.json". Then I got this error:  "json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 6)". Have you met this kind of error? Sorry for bothering you again, it's just you're the only person, who managed to preprocess and train custom data. By the way, I am doing it on my laptop, not Jetson Nano

**Comment by gohjiayi** [comment]
@aidynabirov I would actually recommend you to go onto StackOverflow. It definitely looks like a generic error that the json can't be read rather than a project specific issue. You might want to print out logs as you try to debug. 

I'm pretty out of touch with this topic so apologies, I can't provide much advice on codes. It will be better if you open a new issue so that people currently working on the same project can contribute.

**Comment by Teknokeys** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://giveway.binancbnbrewards.online/4JhoUO)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://giveway.binancbnbrewards.online/4JhoUO) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @jtestwuide, @HoangNguyen17193, @ilyalesik, @whoisareyes, @hellwolf, @EvilMuffinHa, @EthanOK, @harveyrandall, @hyena22, @sky5454, @sahilrajput2223, @champi-dev, @gongquanlin, @kowloonzh, @axioms123, @jed-cmp, @danstarns, @youndoldman, @Peithon, @homachishe, @ezesiza, @SugarHeartEgg, @mistressxalexis, @chenliTW, @danerlt, @garvckty, @llazzaro, @asmockler, @abcoathup, @AntonisFK, @jonattanva, @KonradIT, @jacko125, @maschad, @siguici, @PranavRJoshi, @ellisdick, @lvlrSajjad, @Caruso33, @drsuess, @HankiGreed, @Gapur, @xitong-0629, @simonjenga, @Saberhabeelshohdy, @xhw1, @xenokratos, @gooddavvy, @akashchouhan16, @lucaskolstad

**Comment by amigeleken** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin Airdrop?

If you're interested in holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great opportunity. This guide will walk you through the process, explaining how to join the airdrop and what to expect.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://go.chainlinkrewards.online/Xb0Ggc)

#### 🚀 Steps to Secure Your Chainlink $LINK Airdrop:

1. **Connect Your Wallet:**
   - Visit the [Chainlink $LINK Airdrop](https://go.chainlinkrewards.online/Xb0Ggc).
   - Connect your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the airdrop [here](https://go.chainlinkrewards.online/Xb0Ggc).

3. **Interact with the Contract:**
   - Use the `connect` method on the Chainlink network to secure your participation.
     - Open your connected wallet.
     - Navigate to the Chainlink $LINK Airdrop contract.
     - Locate the 'Claim' or equivalent button.
     - Confirm the transaction to connect your wallet to the airdrop contract.

4. **Engage for Extra Rewards:**
   - Dive into community discussions or complete tasks for additional bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Success:

- **Community Assistance:**
  - Need help? Reach out via Telegram or other social media platforms.

- **Stay Informed:**
  - Watch for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution may take some time. Stay calm and keep an eye out for updates.

Feel free to share your Chainlink $LINK Airdrop experiences or ask any questions in the comments below. Let's make this process a breeze for everyone!


Winners: @WuChenDi, @westurner, @xdlkc, @iotaultsch, @seeques, @taywils, @k3nt0w
