### ISSUE TITLE
Jetson Nano: AttributeError: 'NoneType' object has no attribute 'create_execution_context

### ISSUE THREAD

**Issue by lesreaper** [smellslikeml/ActionAI#46]
System:
Jetson Nano on Jetpack 4.5
CUDA 10.2
TensorRT 8
PyTorch 1.8, TorchVision 0.9.0
Tensorflow 2.4.0

Verified USB Webcam is working with OpenCV and Tensorflow TRT Yolo model in same virtual environment.

Went through all the installation procedures, and getting this error when running:
`python iva.py 0`

```
optimized model path: /home/nvidia/ActionAI/models/resnet18_baseline_att_224x224_A_epoch_249_trt.pth
[TensorRT] ERROR: coreReadArchive.cpp (31) - Serialization Error in verifyHeader: 0 (Magic tag does not match)
[TensorRT] ERROR: INVALID_STATE: std::exception
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
Traceback (most recent call last):
  File "iva.py", line 42, in <module>
    model_trt.load_state_dict(torch.load(OPTIMIZED_MODEL))
  File "/home/nvidia/.virtualenvs/py3tf23cv4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1209, in load_state_dict
    load(self)
  File "/home/nvidia/.virtualenvs/py3tf23cv4/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1204, in load
    state_dict, prefix, local_metadata, True, missing_keys, unexpected_keys, error_msgs)
  File "/home/nvidia/.virtualenvs/py3tf23cv4/lib/python3.6/site-packages/torch2trt-0.2.0-py3.6-linux-aarch64.egg/torch2trt/torch2trt.py", line 454, in _load_from_state_dict
    self.context = self.engine.create_execution_context()
AttributeError: 'NoneType' object has no attribute 'create_execution_context'
```
There is an [article on nVIdia](https://forums.developer.nvidia.com/t/tensorrt-error-rtsafe-corereadarchive-cpp-31-serialization-error-in-verifyheader-0-magic-tag-does-not-match/81872) which says this could be to mismatching input sizes, though I don't see how that could be. The other thing is it could be a TensorRT incompatibility. 

Has anyone been able to get this running on a Jetson Nano with the Jetpack 4.5? Any ideas out there?

**Comment by adrienbeaussier** [comment]
Hello @lesreaper,

Did you manage to solve the issue ? I've got the same running on Jetson AGX Xavier and Jetpack 4.5

**Comment by alice929** [comment]
Have you solved the above problem？
